run:
  # The default concurrency value is the number of available CPU.
  concurrency: 4
  
  # Timeout for analysis, e.g. 30s, 5m.
  timeout: 5m

  # Exit code when at least one issue was found.
  # Default: 1
  issue-exit-code: 1

  # Include test files or not.
  # Default: true
  tests: true

  # Enables skipping of directories:
  # - vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  # Default: true
  skip-dirs-use-default: true

  # Default empty, allowed options are readonly, vendor and mod. 
  modules-download-mode: vendor

  # Define the Go version limit.
  # Mainly related to generics support since go1.18.
  # Default: use Go version from the go.mod file, fallback on the env var `GOVERSION`, fallback on 1.18
  # Intentionally left empty to use go.mod's Go version
  go: ""

linters:
  # Disable all linters.
  # Default: false
  disable-all: true

  # Run only fast linters from enabled linters set (first run won't be fast)
  # Default: false
  fast: false
  
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dogsled
    - errcheck
    - exportloopref
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - gomnd
    - gosimple
    - govet
    - ineffassign
    - misspell
    - paralleltest
    - staticcheck
    - typecheck
    - unused
    - wsl
