{{ if .Values.rbac.create -}}
  {{ if .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cosi-driver.serviceAccountName" . }}
  labels:
    {{ include "cosi-driver.labels" . }}
    {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{ toYaml . }}
    {{- end }}
  {{- end }}
{{- end}}