// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package config

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// this file contains JSON schema for Dell COSI Driver Configuration file
type ConfigSchemaJson struct {
	// List of connections to object storage platforms that can be used for object
	// storage provisioning.
	Connections []Configuration `json:"connections,omitempty" yaml:"connections,omitempty" mapstructure:"connections,omitempty"`
}

// Configuration for single connection to object storage platform that is used for
// object storage provisioning
type Configuration struct {
	// Objectscale corresponds to the JSON schema field "objectscale".
	Objectscale *Objectscale `json:"objectscale,omitempty" yaml:"objectscale,omitempty" mapstructure:"objectscale,omitempty"`
}

// Credentials used for authentication to object storage provider
type Credentials struct {
	// Password for object storage provider
	Password string `json:"password" yaml:"password" mapstructure:"password"`

	// Username for object storage provider
	Username string `json:"username" yaml:"username" mapstructure:"username"`
}

// Configuration specific to the ObjectScale platform
type Objectscale struct {
	// Credentials corresponds to the JSON schema field "credentials".
	Credentials Credentials `json:"credentials" yaml:"credentials" mapstructure:"credentials"`

	// Indicates if the contents of the bucket should be emptied as part of the
	// deletion process
	EmptyBucket bool `json:"emptyBucket,omitempty" yaml:"emptyBucket,omitempty" mapstructure:"emptyBucket,omitempty"`

	// Default, unique identifier for the single connection.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Endpoint of the ObjectScale VDC Management Internal service
	MgmtEndpoint string `json:"mgmt-endpoint" yaml:"mgmt-endpoint" mapstructure:"mgmt-endpoint"`

	// Namespace associated with the user/tenant that is allowed to access the bucket
	Namespace *string `json:"namespace,omitempty" yaml:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Protocols corresponds to the JSON schema field "protocols".
	Protocols Protocols `json:"protocols" yaml:"protocols" mapstructure:"protocols"`

	// Identity and Access Management (IAM) API specific field, points to the region
	// in which object storage provider is installed
	Region *string `json:"region,omitempty" yaml:"region,omitempty" mapstructure:"region,omitempty"`

	// Tls corresponds to the JSON schema field "tls".
	Tls Tls `json:"tls" yaml:"tls" mapstructure:"tls"`
}

// Protocols supported by the connection
type Protocols struct {
	// S3 corresponds to the JSON schema field "s3".
	S3 *S3 `json:"s3,omitempty" yaml:"s3,omitempty" mapstructure:"s3,omitempty"`
}

// S3 configuration
type S3 struct {
	// Endpoint of the ObjectStore S3 service
	Endpoint string `json:"endpoint" yaml:"endpoint" mapstructure:"endpoint"`
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *S3) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if v, ok := raw["endpoint"]; !ok || v == nil {
		return fmt.Errorf("field endpoint in S3: required")
	}
	type Plain S3
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = S3(plain)
	return nil
}

// TLS configuration details
type Tls struct {
	// Base64 encoded content of the clients's certificate file
	ClientCert *string `json:"client-cert,omitempty" yaml:"client-cert,omitempty" mapstructure:"client-cert,omitempty"`

	// Base64 encoded content of the clients's key certificate file
	ClientKey *string `json:"client-key,omitempty" yaml:"client-key,omitempty" mapstructure:"client-key,omitempty"`

	// Controls whether a client verifies the server's certificate chain and host name
	Insecure bool `json:"insecure" yaml:"insecure" mapstructure:"insecure"`

	// Base64 encoded content of the root certificate authority file
	RootCas *string `json:"root-cas,omitempty" yaml:"root-cas,omitempty" mapstructure:"root-cas,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Tls) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["insecure"]; !ok || v == nil {
		return fmt.Errorf("field insecure in Tls: required")
	}
	type Plain Tls
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Tls(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Tls) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if v, ok := raw["insecure"]; !ok || v == nil {
		return fmt.Errorf("field insecure in Tls: required")
	}
	type Plain Tls
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Tls(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *S3) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["endpoint"]; !ok || v == nil {
		return fmt.Errorf("field endpoint in S3: required")
	}
	type Plain S3
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = S3(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Objectscale) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["credentials"]; !ok || v == nil {
		return fmt.Errorf("field credentials in Objectscale: required")
	}
	if v, ok := raw["id"]; !ok || v == nil {
		return fmt.Errorf("field id in Objectscale: required")
	}
	if v, ok := raw["mgmt-endpoint"]; !ok || v == nil {
		return fmt.Errorf("field mgmt-endpoint in Objectscale: required")
	}
	if v, ok := raw["protocols"]; !ok || v == nil {
		return fmt.Errorf("field protocols in Objectscale: required")
	}
	if v, ok := raw["tls"]; !ok || v == nil {
		return fmt.Errorf("field tls in Objectscale: required")
	}
	type Plain Objectscale
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if v, ok := raw["emptyBucket"]; !ok || v == nil {
		plain.EmptyBucket = false
	}
	*j = Objectscale(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Objectscale) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if v, ok := raw["credentials"]; !ok || v == nil {
		return fmt.Errorf("field credentials in Objectscale: required")
	}
	if v, ok := raw["id"]; !ok || v == nil {
		return fmt.Errorf("field id in Objectscale: required")
	}
	if v, ok := raw["mgmt-endpoint"]; !ok || v == nil {
		return fmt.Errorf("field mgmt-endpoint in Objectscale: required")
	}
	if v, ok := raw["protocols"]; !ok || v == nil {
		return fmt.Errorf("field protocols in Objectscale: required")
	}
	if v, ok := raw["tls"]; !ok || v == nil {
		return fmt.Errorf("field tls in Objectscale: required")
	}
	type Plain Objectscale
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if v, ok := raw["emptyBucket"]; !ok || v == nil {
		plain.EmptyBucket = false
	}
	*j = Objectscale(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Credentials) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if v, ok := raw["password"]; !ok || v == nil {
		return fmt.Errorf("field password in Credentials: required")
	}
	if v, ok := raw["username"]; !ok || v == nil {
		return fmt.Errorf("field username in Credentials: required")
	}
	type Plain Credentials
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = Credentials(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Credentials) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["password"]; !ok || v == nil {
		return fmt.Errorf("field password in Credentials: required")
	}
	if v, ok := raw["username"]; !ok || v == nil {
		return fmt.Errorf("field username in Credentials: required")
	}
	type Plain Credentials
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Credentials(plain)
	return nil
}
