name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  tests-workflow:
    uses: ./.github/workflows/dev.yaml

  gitavscan:
    runs-on: ubuntu-latest
    name: AV scan
    steps:
    - uses: actions/checkout@v3
    - name: Git AV Scan
      uses: djdefi/gitavscan@main

  image-scans:
    runs-on: ubuntu-latest
    env:
      IMAGETAG: "${{ github.ref_name }}"
      IMAGENAME: "cosi-driver"
      REGISTRY: "sample_registry" # TODO: There is no registry for now
    steps:
      - name: Run trivy action
        uses: aquasecurity/trivy-action@v0.10.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGENAME }}:${{ env.IMAGETAG }}
          exit-code: 1
      - name: Run dockle action
        uses: erzz/dockle-action@v1.3.1
        env:
          DOCKER_CONTENT_TRUST: 1
        with:
          exit-code: 1
          image: ${{ env.REGISTRY }}/${{ env.IMAGENAME }}:${{ env.IMAGETAG }}
